<!-- The Styles -->
<!-- Layout Styles -->
<?= stylesheet_link_tag('mango/style') ?>
<?= stylesheet_link_tag('mango/grid') ?>
<?= stylesheet_link_tag('mango/layout') ?>

<!-- Icon Styles -->
<?= stylesheet_link_tag('mango/icons') ?>
<?= stylesheet_link_tag('mango/fonts/font-awesome') ?>

<!--[if IE 8]><?= stylesheet_link_tag('mango/fonts/font-awesome-ie7') ?><![endif]-->

<!-- External Styles -->
<?= stylesheet_link_tag('mango/external/jquery-ui-1.8.21.custom') ?>

<?= stylesheet_link_tag('mango/external/jquery-ui-1.8.21.custom') ?>
<?= stylesheet_link_tag('mango/external/jquery.chosen') ?>
<?= stylesheet_link_tag('mango/external/jquery.cleditor') ?>
<?= stylesheet_link_tag('mango/external/jquery.colorpicker') ?>
<?= stylesheet_link_tag('mango/external/jquery.elfinder') ?>
<?= stylesheet_link_tag('mango/external/jquery.fancybox') ?>
<?= stylesheet_link_tag('mango/external/jquery.jgrowl') ?>
<?= stylesheet_link_tag('mango/external/jquery.plupload.queue') ?>
<?= stylesheet_link_tag('mango/external/syntaxhighlighter/shCore') ?>
<?= stylesheet_link_tag('mango/external/syntaxhighlighter/shThemeDefault') ?>

<!-- Elements -->
<?= stylesheet_link_tag('mango/elements') ?>
<?= stylesheet_link_tag('mango/forms') ?>

<!-- OPTIONAL: Print Stylesheet for Invoice -->
<?= stylesheet_link_tag('mango/print-invoice') ?>

<!-- Typographics -->
<?= stylesheet_link_tag('mango/typographics') ?>

<!-- Responsive Design -->
<?= stylesheet_link_tag('mango/media-queries') ?>

<!-- Bad IE Styles -->
<?= stylesheet_link_tag('mango/ie-fixes') ?>