<?= Load::lib("html"); ?>
<!-- The footer -->
<footer class="container_12">
	<ul class="grid_6">
		<li>
			<?= Html::link("http://www.emisionfiscal.com/mx/index.php/planes", "Planes", "target: _blank") ?>
		</li>
		<li>
			<?= Html::link("http://www.emisionfiscal.com/mx/index.php/privacidad", "Pol&iacute;tica de Privacidad", "target: _blank") ?>
		</li>
		<li>
			<?= Html::link("http://www.emisionfiscal.com/mx/index.php/terminos-y-condiciones", "T&eacute;rminos y Condiciones", "target: _blank") ?>
		</li>
	</ul>

	<span class="grid_6"> Copyright &copy; 2013 Emisión Fiscal</span>
</footer><!-- End of footer -->