<?= Load::lib("html"); ?>
<!-- The footer -->
<footer class="container_12">
	<ul class="grid_6">
		<li>
			<?= Html::link("main/planes", "Planes", "target: _blank") ?>
		</li>
		<li>
			<?= Html::link("main/privacidad", "Pol&iacute;tica de Privacidad", "target: _blank") ?>
		</li>
		<li>
			<?= Html::link("main/condiciones", "T&eacute;rminos y Condiciones", "target: _blank") ?>
		</li>
	</ul>

	<span class="grid_6"> Copyright &copy; 2012 Ciberfactura - 6KSoft S.A. de C.V. </span>
</footer><!-- End of footer -->