<!-- The header containing the logo -->
<header class="container_12">
    <!-- Your logos -->
    <?= Load::lib("html"); ?>
    <?= Html::link("mango/index", Html::imagen("logo.png","Emisión Fiscal")) ?>
    <?= Html::link("mango/index",Html::imagen("logo-mobile.png","Mango",22,70),"class: phone-title") ?>

    <div class="buttons">
    	<?php if(Session::get("tipo_usuario") == "CLIENTE"){ ?>
	    	<?= Html::linkAjax("clientes", '<span class="icon icon-group"></span> Clientes', "contenido") ?>
	        <?= Html::linkAjax("productos", '<span class="icon icon-barcode"></span> Productos', "contenido") ?>
	        <?= Html::linkAjax("facturacion", '<span class="icon icon-barcode"></span> Facturacion', "contenido") ?>
	    <?php } ?>
	    <?php if(Session::get("tipo_usuario") == "ADMIN"){ ?>
	    	<?= Html::linkAjax("cuentas", '<span class="icon icon-group"></span> Cuentas', "contenido") ?>
	        <?= Html::linkAjax("paquetes", '<span class="icon icon-barcode"></span> Paquetes', "contenido") ?>
	    <?php } ?>
        <!-- <?= Html::linkAjax("ventas", '<span class="icon icon-shopping-cart"></span> Ventas', "contenido") ?> -->
        <!-- <?= Html::linkAjax("facturacion", '<span class="icon icon-table"></span> Facturaci&oacute;n', "contenido") ?> -->
        <!-- <?= Html::linkAjax("main/formularios", '<span class="icon icon-credit-card"></span> Formularios', "contenido") ?> -->
        <!-- <?= Html::linkAjax("main/tablas", '<span class="icon icon-sitemap"></span> Tablas', "contenido") ?> -->
    </div><!-- End of .buttons -->
</header><!-- End of header -->