<!-- The header containing the logo -->
<header class="container_12">
    <!-- Your logos -->
    <?= Load::lib("html"); ?>
    <?= Html::link("mango/index", Html::imagen("logo.png","Mango",191,60)) ?>
    <?= Html::link("mango/index",Html::imagen("logo-mobile.png","Mango",22,70),"class: phone-title") ?>

    <div class="buttons">
    	<?= Html::linkAjax("clientes", '<span class="icon icon-group"></span> Clientes', "contenido") ?>
        <?= Html::linkAjax("productos", '<span class="icon icon-barcode"></span> Productos', "contenido") ?>
        <!-- <?= Html::linkAjax("ventas", '<span class="icon icon-shopping-cart"></span> Ventas', "contenido") ?> -->
        <!-- <?= Html::linkAjax("facturacion", '<span class="icon icon-table"></span> Facturaci&oacute;n', "contenido") ?> -->
        <!-- <?= Html::linkAjax("main/formularios", '<span class="icon icon-credit-card"></span> Formularios', "contenido") ?> -->
        <!-- <?= Html::linkAjax("main/tablas", '<span class="icon icon-sitemap"></span> Tablas', "contenido") ?> -->
    </div><!-- End of .buttons -->
</header><!-- End of header -->