<script language=""JavaScript" ">
	$(document).ready(function(){
		$("a#menu1").click(function(){
			$("li.current").removeClass("current");
			$("li#"+$("a#menu1").attr("id")).addClass("current");
		});
		
		$("a#menu2").click(function(){
			$("li.current").removeClass("current");
			$("li#"+$("a#menu2").attr("id")).addClass("current");
		});
	});
</script>
<!-- The sidebar -->
<aside>
	<div class="top">
		<!-- Navigation -->
		<nav>
			<ul class="collapsible accordion">
				<?php $menus = Menu::reporte("tipo= 'CLIENTE' AND activo = 'SI'","orden ASC"); ?>
				<?php if($menus) foreach($menus as $menu){ ?>
					<li id="menu<?= $menu -> id ?>">
						<?= Html::link("javascript:void(0);", Html::imagen($menu -> imagen,$menu -> nombre,16,16).$menu -> nombre,"class: ".($menu -> abierto == "SI" ? "open" : "close")) ?>
					<?php $secciones = $menu -> secciones() ?>
					<?php if($secciones){ ?>
						<ul>
						<?php foreach($secciones as $seccion){ ?>
							<li>
								<?= Html::linkAjax($seccion -> link, Html::imagen($seccion -> imagen,($seccion -> nombre),16,16).($seccion -> nombre).'<span class="icon"></span>', $seccion -> contenedor, "id: menu".$menu -> id) ?>
							</li>
						<?php } ?>
						</ul>	
					<?php } ?>
					</li>
				<?php } ?>
			</ul>
		</nav><!-- End of nav -->
	</div><!-- End of .top -->

	<div class="bottom sticky">
		<div class="divider"></div>
		<div class="progress">
			<div class="bar" data-title="Facturas" data-value="360" data-max="365"></div>
			<div class="bar" data-title="Usuarios" data-value="3" data-max="5" data-format="0 MB"></div>
			<div class="bar" data-title="Disco Duro" data-value="1782" data-max="5120" data-format="0,0 MB"></div>
		</div>
		<div class="divider"></div>
		<div class="buttons">
			<a href="javascript:void(0);" class="button grey open-add-client-dialog">Ticket de Soporte</a>
			<a href="javascript:void(0);" class="button grey open-add-client-dialog">Upgrade / Downgrade</a>
		</div>
	</div><!-- End of .bottom -->
</aside><!-- End of sidebar -->