<script language=""JavaScript" ">
	$(document).ready(function(){
		$("a#menu1").click(function(){
			$("li.current").removeClass("current");
			$("li#"+$("a#menu1").attr("id")).addClass("current");
		});
		
		$("a#menu2").click(function(){
			$("li.current").removeClass("current");
			$("li#"+$("a#menu2").attr("id")).addClass("current");
		});
	});
</script>
<!-- The sidebar -->
<aside>
	<div class="top">
		<!-- Navigation -->
		<nav>
			<ul class="collapsible accordion">
				<?php $menus = Menu::reporte("tipo= 'CLIENTE' AND activo = 'SI'","orden ASC"); ?>
				<?php if($menus) foreach($menus as $menu){ ?>
					<?php
						$cuenta = Cuenta::consultar(Session::get("cuenta_id"));
						$paquete = $cuenta -> paquete();
						
						if($paquete -> multiple_sucursal == "NO" && strtoupper($menu -> nombre) == "SUCURSALES"){
							continue;
						}
						
						if($paquete -> multiple_moneda == "NO" && strtoupper($menu -> nombre) == "MONEDAS"){
							continue;
						}
					?>
					<li id="menu<?= $menu -> id ?>">
						<?= Html::link("javascript:void(0);", Html::imagen($menu -> imagen,$menu -> nombre,16,16).$menu -> nombre,"class: ".($menu -> abierto == "SI" ? "open" : "close")) ?>
					<?php $secciones = $menu -> secciones() ?>
					<?php if($secciones){ ?>
						<ul>
						<?php foreach($secciones as $seccion){ ?>
							<li>
								<?= Html::linkAjax($seccion -> link, Html::imagen($seccion -> imagen,($seccion -> nombre),16,16).($seccion -> nombre).'<span class="icon"></span>', $seccion -> contenedor, "id: menu".$menu -> id) ?>
							</li>
						<?php } ?>
						</ul>	
					<?php } ?>
					</li>
				<?php } ?>
			</ul>
		</nav><!-- End of nav -->
	</div><!-- End of .top -->
	<!--
	<div class="bottom sticky">
		<div class="divider"></div>
		<div class="progress">
			<?php Load::lib("estadistica"); ?>
			<?php $paquete = Paquete::consultar(Session::get("paquete_id")) ?>
			<div class="bar" data-title="Facturas" data-value="<?= Estadistica::facturas(Session::get("cuenta_id"),date("mY")) ?>" data-max="<?= $paquete -> facturas_incluidas ?>"></div>
			<div class="bar" data-title="Almacenamiento" data-value="<?= Estadistica::almacenamiento(Session::get("cuenta_id")) ?>" data-max="<?= $paquete -> almacenamiento ?>"></div>
			<div class="bar" data-title="Usuarios" data-value="<?= Estadistica::usuarios(Session::get("cuenta_id")) ?>" data-max="<?= $paquete -> usuarios ?>"></div>
		</div>
		<div class="divider"></div>
		
		<div class="buttons">
			<a href="javascript:void(0);" class="button grey open-add-client-dialog">Ticket de Soporte</a>
			<a href="javascript:void(0);" class="button grey open-add-client-dialog">Upgrade / Downgrade</a>
		</div>

	</div>
	-->
</aside><!-- End of sidebar -->