<script language=""JavaScript" ">
	$(document).ready(function(){
		$("a#menu1").click(function(){
			$("li.current").removeClass("current");
			$("li#"+$("a#menu1").attr("id")).addClass("current");
		});
		
		$("a#menu2").click(function(){
			$("li.current").removeClass("current");
			$("li#"+$("a#menu2").attr("id")).addClass("current");
		});
	});
</script>
<!-- The sidebar -->
<?php //echo Session::get("tipo_facturacion"); ?>
<aside>
	<div class="top">
		<!-- Navigation -->
		<nav>
			<ul class="collapsible accordion">
				<?php 
					$menus = Menu::reporte("(tipo ='".Session::get("tipo_usuario")."' OR tipo ='".Session::get("tipo_facturacion")."') AND activo = 'SI'","orden ASC");
				?>
				<?php if($menus) foreach($menus as $menu){ ?>
					<?php
						if(Session::get("cuenta_id")>0){
							$cuenta = Cuenta::consultar(Session::get("cuenta_id"));
							if($cuenta){
								$paquete = $cuenta -> paquete();
								
								if($paquete -> multiple_sucursal == "NO" && strtoupper($menu -> nombre) == "SUCURSALES"){
									continue;
								}
							}
							
							//QUITADA VALIDACION QUE OCULTA MENUS DE MONEDA MIENTRAS NO SE DESARROLLE ADECUADAMENTE
							if(/*$paquete -> multiple_moneda == "NO" && */strtoupper($menu -> nombre) == "MONEDAS"){
								continue;
							}
						}
					?>
					<li id="menu<?= $menu -> id ?>">
						<?= Html::link("javascript:void(0);", Html::imagen($menu -> imagen,$menu -> nombre,16,16).$menu -> nombre,"class: ".($menu -> abierto == "SI" ? "open" : "close")) ?>
					<?php $secciones = $menu -> secciones() ?>
					<?php if($secciones){ ?>
						<ul>
						<?php foreach($secciones as $seccion){ ?>
							<?php
								if(/*$paquete -> multiple_moneda == "NO" && */strtoupper($seccion -> nombre) == "MONEDAS"){
									continue;
								}
							?>
							<li>
								<?= Html::linkAjax($seccion -> link, Html::imagen($seccion -> imagen,($seccion -> nombre),16,16).($seccion -> nombre).'<span class="icon"></span>', $seccion -> contenedor, "id: menu".$menu -> id) ?>
							</li>
						<?php } ?>
						</ul>	
					<?php } ?>
					</li>
				<?php } ?>
			</ul>
		</nav><!-- End of nav -->
	</div><!-- End of .top -->
	<?php if(Session::get("tipo_usuario")=="CLIENTE"){ ?>
	<div class="bottom">
		<div class="divider"></div>
		<div class="progress">
			<?php Load::lib("estadistica"); ?>
			<?php $paquete = Paquete::consultar(Session::get("paquete_id")) ?>
			<div class="bar" data-title="Facturas" data-value="<?= Estadistica::facturas(Session::get("cuenta_id"),date("mY")) ?>" data-max="<?= $paquete -> facturas_incluidas ?>"></div>
			<div class="bar" data-title="Almacenamiento (MB)" data-value="<?= Estadistica::almacenamiento(Session::get("cuenta_id")) ?>" data-max="<?= $paquete -> almacenamiento ?>"></div>
			<div class="bar" data-title="Usuarios" data-value="<?= Estadistica::usuarios(Session::get("cuenta_id")) ?>" data-max="<?= $paquete -> usuarios ?>"></div>
		</div>
		<div class="divider"></div>
		
		<div class="buttons">
			<a href="javascript:void(0);" class="button blue open-dialogo_nuevo_ticket">Ticket de Soporte</a>
			<!--<a href="javascript:void(0);" class="button grey open-add-client-dialog">Actualizar Plan</a>-->
		</div>
	</div>
	<?php } ?>
		<?php if(Session::get("tipo_usuario")=="ADMIN"){ ?>
	<div class="bottom">
		<div class="divider"></div>		
		<div class="buttons">
			<a href="javascript:void(0);" class="button blue open-dialogo_nuevo_mensaje">Enviar Mensaje</a>
			<!--<a href="javascript:void(0);" class="button grey open-add-client-dialog">Actualizar Plan</a>-->
		</div>
	</div>
	<?php } ?>
</aside><!-- End of sidebar -->
