<!-- The lock screen -->
<div id="lock-screen" title="">

    <?= Html::link("mango/index","Cerrar Sesión","class: header right button grey flat"); ?>
    <p><?= "Debido a la inactividad de la sesión, su cuenta se ha bloqueado temporalmente." ?></p>
    <p><?= "Para desbloquear su cuenta, basta con deslizar el botón e introduzca su contraseña." ?></p>

    <div class="actions">
        <div id="slide_to_unlock">
            <?= Html::imagen("elements/slide-unlock/lock-slider.png","Deslizame"); ?>
            <span>Deslizar</span>
        </div>
        <?= Formulario::inicio("#") ?>
            <?= Formulario::password("pwd","",utf8_encode("placeholder: Ingresa tu contraseña..."),"autocorrect: off","autocapitalize: off") ?>
            <?= Formulario::submit("Aceptar","name: send", "disabled: disabled") ?>
            <?= Formulario::reset("X"); ?>
        <?= Formulario::fin() ?>
    </div><!-- End of .actions -->

</div><!-- End of lock screen -->
<script language="JavaScript">
	function breadcrumb(acciones,titulos){
		var secciones = acciones.split("/",2);
		var textos = titulos.split("/",2);
		
		var tmp1 = '<a id="jsRemote" rel="#contenido" class="jsRemote" href="<?= PROYECTO_BASE ?>'+secciones[0]+'">'+textos[0]+'</a>';
		var tmp2 = '<a id="jsRemote" rel="#contenido" class="jsRemote" href="<?= PROYECTO_BASE ?>'+secciones[0]+'/'+secciones[1]+'">'+textos[1]+'</a>';
		
		$("li#breadcrumb_controlador").html(tmp1);
		$("li#breadcrumb_accion").html(tmp2);
	}
	
	function breadcrumbParameters(acciones,titulos,parametros){
		var secciones = acciones.split("/",2);
		var textos = titulos.split("/",2);
		
		var tmp1 = '<a id="jsRemote" rel="#contenido" class="jsRemote" href="<?= PROYECTO_BASE ?>'+secciones[0]+'">'+textos[0]+'</a>';
		var tmp2 = '<a id="jsRemote" rel="#contenido" class="jsRemote" href="<?= PROYECTO_BASE ?>'+secciones[0]+'/'+secciones[1]+'/'+parametros+'">'+textos[1]+'</a>';
		
		$("li#breadcrumb_controlador").html(tmp1);
		$("li#breadcrumb_accion").html(tmp2);
	}
</script>
<!-- The toolbar at the top -->
<section id="toolbar">
	<div class="container_12">

		<!-- Left side -->
		<div class="left">
			<ul class="breadcrumb">
				<li><?= Html::link(APLICACION_URL, "Emisión Fiscal") ?></li>
				<li><?= Html::linkAjax("configuracion/fiscal", Session::get("empresa"),"contenido") ?></li>
				<li id="breadcrumb_controlador">
					<?= Html::linkAjax("configuracion/index", "Página Principal","contenido") ?>
				</li>
				<li id="breadcrumb_accion">
					<?= Html::linkAjax("configuracion/index", "Inicio","contenido") ?>
				</li>
			</ul>
		</div>
		<!-- End of .left -->

		<!-- Right side -->
		<div class="right">
			<ul>
				<!--
					<li>
						<?= Html::link("mango/index", '<span class="icon i14_admin-user"></span>Perfil'); ?>
					</li>
				-->
				<?php $n = Ticket::total("cuenta_id = ".Session::get("cuenta_id")." AND admin = 'SI' AND respondido = 'NO' AND estado = 'OK'") ?>
				<?php if($n > 0 && Session::get("tipo_usuario") == "CLIENTE"){ ?>
				<li>
					<?= Html::link("main/mensajes", '<span class="no_mensajes" rel="main/numero_mensajes">'.$n.'</span>Mensajes',"class: mensajes"); ?>

					<div class="popup">
						<h3>Mensajes Nuevos</h3>

						<?= Html::link("#", "Cerrar", "class: button flat left grey","onclick: $(this).parent().fadeToggle($$.config.fxSpeed)") ?>
						<?= Html::link("mango/index", "Inbox", "class: button flat right") ?>

						<div class="content mail">
							<ul>
								<?php $mensajes = Ticket::reporte("cuenta_id = ".Session::get("cuenta_id")." AND admin = 'SI' AND respondido = 'NO' AND estado = 'OK'"); ?>
								<?php if($mensajes) foreach($mensajes as $mensaje){ ?>
									<li>
										<div class="avatar">
											<?= Html::imagen("elements/mail/mail.png","",40,40) ?>
										</div>
										<div class="info">
											<strong><?= $mensaje -> admin_nombre ?></strong>
											<span><?= $mensaje -> asunto ?></span>
											<small><?= Formato::fecha($mensaje -> fecha)." ".substr($mensaje -> fecha,11,5) ?></small>
										</div>
										<div class="text">
											<br><div><?= substr($mensaje -> mensaje,0,200)." ..." ?></div><br>
											<div class="actions">
												<?= Html::link("main/mensajes/".$mensaje -> id, "Responder", "class: left mensajero") ?>
												<?= Html::link("main/cerrar_mensaje/".$mensaje -> id, "Borrar", "class: red right borrar_mensaje", "onclick: $(this).parent().parent().parent().slideToggle($$.config.fxSpeed)")?>
											</div>
										</div>
									</li>
								<?php } ?>
							</ul>
						</div>
					</div>
				</li>
				<li class="space"></li>
				<?php } ?>
			<!--
				<li>
				    <?= Html::link("javascript:void(0);","<span>--:--</span>Bloquear","id: btn-lock"); ?>
				</li>
			-->
				<li class="red">
				    <?= Html::link("logout","Cerrar Sesi&oacute;n"); ?>
				</li>

			</ul>
		</div><!-- End of .right -->

		<!-- Phone only items -->
		<div class="phone">

			<!-- User Link -->
			<li>
				<a href="pages_profile.html"><span class="icon icon-user"></span></a>
			</li>
			<!-- Navigation -->
			<li>
				<a class="navigation" href="#"><span class="icon icon-list"></span></a>
			</li>

		</div><!-- End of phone items -->

	</div><!-- End of .container_12 -->
</section><!-- End of #toolbar -->
<div id="clear"></div>
<script language="JavaScript">
	$( document ).ready(function() {
		$('.mensajero').click(function( e ) {
	 		e.preventDefault();
	 		
	 		$('.popup').hide();
	 		
	 		$("#contenido").html('<div align="center" style="padding: 50px;"><img src="http://localhost/aspos/app/public/img/loader.gif" /><br><b>Cargando...</b></div>');
	 		
	 		$("#contenido").load($(this).attr("href"));
	 		
	    });
	 
	 	$('.borrar_mensaje').click(function( e ) {
	 		e.preventDefault();
	 		
	 		$("#clear").html('<div align="center" style="padding: 50px;"><img src="http://localhost/aspos/app/public/img/loader.gif" /><br><b>Cargando...</b></div>');
	 		
	 		$("#clear").load($(this).attr("href"));
	 	});
	});
</script>