<!-- The blue toolbar stripe -->
<section class="toolbar">
	<div class="user">
		<div class="avatar">
			<?= Html::imagen("layout/content/toolbar/user/avatar.png") ?>
			<!-- <span>7</span> -->
		</div>
		<span>Configuraci&oacute;n</span>
		<nav>
		<ul>
			<li>
				<?= Html::linkAjax("configuracion/index", "General","contenido") ?>
			</li>
			<li class="line"></li>
			<li>
				<?= Html::linkAjax("unidades/reporte", "Unidades","contenido") ?>
			</li>
			<li>
				<?= Html::linkAjax("impuestos/reporte", "Impuestos","contenido") ?>
			</li>
			<li>
				<?= Html::linkAjax("monedas/reporte", "Monedas","contenido") ?>
			</li>
			<li class="line"></li>
			<li>
				<?= Html::linkAjax("usuarios/reporte", "Usuarios","contenido") ?>
			</li>
			<!--
			<li>
				<?= Html::linkAjax("roles/index", "Roles","contenido") ?>
			</li>
			-->
			
			<li class="line"></li>
			<li>
				<?= Html::linkAjax("configuracion/fiscal", "Información Fiscal","contenido") ?>
			</li>
			<li>
				<?= Html::linkAjax("cbb/folios", "Series / Folios","contenido") ?>
			</li>
			<li class="line"></li>
			<li>
				<?= Html::link("logout", "Cerrar Sesi&oacute;n") ?>
			</li>
		</ul>
		</nav>
	</div>
	<!-- Possible sizes: small/medium/large -->
	<!--
	<ul class="shortcuts">
		<li>
			<?= Html::link("javascript:void(0);", '<span class="icon i24_user"></span>') ?>
			
			<div class="large">
				<?= Formulario::inicioAjax("clientes/registro","contenido",0,"class: full grid") ?>
					<h3>Nuevo Cliente</h3>
	
					<button class="button flat left grey" onclick="$(this).parent().fadeToggle($$.config.fxSpeed).parent().removeClass('active')">
						Cerrar
					</button>
					<input type="submit" class="button flat right" onclick="$(this).parent().fadeToggle($$.config.fxSpeed).parent().removeClass('active')" />
					<div class="content">
						<div class="row no-bg">
							<p class="_100 small">
								<label for="p1_username">Usuario</label>
								<?= Formulario::texto("p1_username") ?>
							</p>
						</div>
						<div class="row no-bg">
							<p class="_50 small">
								<label for="p1_firstname">Nombre(s)</label>
								<?= Formulario::texto("p1_firstname") ?>
							</p>
							<p class="_50 small">
								<label for="p1_lastname">Apellidos</label>
								<?= Formulario::texto("p1_lastname") ?>
							</p>
						</div>
					</div>
				<?= Formulario::fin() ?>
			</div>
		</li>
		<li>
			<?= Html::link("javascript:void(0);", '<span class="icon i24_user-business"></span>') ?>
			<div class="large">
				<h3>Nuevo Proveedor</h3>

				<button class="button flat left grey" onclick="$(this).parent().fadeToggle($$.config.fxSpeed).parent().removeClass('active')">
					Cerrar
				</button>
				<button class="button flat right" onclick="$(this).parent().fadeToggle($$.config.fxSpeed).parent().removeClass('active')">
					Enviar
				</button>

				<div class="content">
					<?= Formulario::inicio("",0,"class: full grid") ?>
						<div class="row no-bg">
							<p class="_100 small">
								<?= Formulario::texto("p1_lastname","","placeholder: Destinatario") ?>
							</p>
							<p class="_100 small">
								<?= Formulario::texto("p1_lastname","","placeholder: Asunto") ?>
							</p>
							<p class="_100 small">
								<?= Formulario::textarea("p2_message","","rows: 5","style: overflow: hidden; height: 45px; width: 100%; -webkit-box-sizing: border-box; -moz-box-sizing: border-box; -ms-box-sizing: border-box; box-sizing: border-box;","placeholder: Mensaje") ?>
							</p>
						</div>
					<?= Formulario::fin() ?>
				</div>
			</div>
		</li>
		<li>
			<?= Html::link("javascript:void(0);", '<span class="icon i24_wooden-box-label"></span>') ?>
			<div class="large">
				<h3>Nuevo Producto</h3>

				<button class="button flat left grey" onclick="$(this).parent().fadeToggle($$.config.fxSpeed).parent().removeClass('active')">
					Cerrar
				</button>
				<button class="button flat right" onclick="$(this).parent().fadeToggle($$.config.fxSpeed).parent().removeClass('active')">
					Enviar
				</button>

				<div class="content">
					<?= Formulario::inicio("",0,"class: full grid") ?>
						<div class="row no-bg">
							<p class="_100 small">
								<?= Formulario::texto("p1_lastname","","placeholder: Destinatario") ?>
							</p>
							<p class="_100 small">
								<?= Formulario::texto("p1_lastname","","placeholder: Asunto") ?>
							</p>
							<p class="_100 small">
								<?= Formulario::textarea("p2_message","","rows: 5","style: overflow: hidden; height: 45px; width: 100%; -webkit-box-sizing: border-box; -moz-box-sizing: border-box; -ms-box-sizing: border-box; box-sizing: border-box;","placeholder: Mensaje") ?>
							</p>
						</div>
					<?= Formulario::fin() ?>
				</div>
			</div>
		</li>
	</ul>
	-->

	<input type="search" data-source="extras/search.php" placeholder="Buscar..." autocomplete="off" class="tooltip" title="Ingresa palabra de busqueda" data-gravity=s>
</section><!-- End of .toolbar-->