<?= Load::lib("html"); ?>
<?= Load::lib("formato"); ?>
<?= Load::lib("formulario"); ?>
<?= Html::breadcrumbs("configuracion/index", "Página Principal/Inicio") ?>

<section id="content" class="container_12 clearfix" data-sort=true>
	<!--
	<ul class="stats not-on-phone">
		<li>
			<strong>61263</strong>
			<small>Total Visits</small>
			<span class=green>+26%</span>
		</li>
		<li>
			<strong>23</strong>
			<small>Orders</small>
			<span class=green>+16%</span>
		</li>
		<li>
			<strong>$2165.57</strong>
			<small>Total Volume</small>
			<span class=red>-8%</span>
		</li>
		<li>
			<strong>0</strong>
			<small>Overdue Tickets</small>
			<span>0%</span>
		</li>
		<li>
			<strong>7</strong>
			<small>Reported Bugs</small>
			<span class=red>+17%</span>
		</li>
	</ul>
	
	
	<h1 class="grid_12 margin-top no-margin-top-phone">Dashboard</h1>
	

	<div class="grid_12 center-elements">
		<div class="full-stats">
			<div class="stat minichart" data-total=16525 data-values="[4,6,7,7,4,3,2,1,4]" data-title=Visits data-format="+0,0;-0,0" data-change=22></div>
		</div>
		<div class="full-stats">
			<div class="stat minichart" data-total=-17 data-values="[2,5,8,7,3,0,-1,-2,-4]" data-title=Users data-format="+0,0;-0,0" data-change=-6></div>
		</div>
		<div class="full-stats">
			<div class="stat minichart" data-total=0 data-values="[0,0,0,1,2,1,-2,-2,-1]" data-title=Orders data-change=0></div>
		</div>
	</div>

	
	<div class="grid_12">
		<div class="box">
		
			<div class="header">
				<h2>
					<?= Html::imagen("miniconos/chart_pie.png","Gráficas",0,0,"class: icon") ?>Graficas</h2>
				
				<a href="javascript:void(0);" class="menu icon-cog"></a>
				<menu>
					<a href="javascript:void(0);" class="open-add-client-dialog"><span class="icon icon-plus"></span>Add Client</a>
					<a href="javascript:void(0);"><div class="icon icon-pencil"></div>Edit</a>
					<a href="javascript:void(0);"><div class="icon icon-remove"></div>Remove</a>
				</menu>
			</div>
			
			<div class="content" style="height: 250px;">
				<table class=chart >
					<thead>
						<tr>
							<th></th>
							<th>Label 1</th>
							<th>Label 2</th>
							<th>Label 3</th>
							<th>Label 4</th>
							<th>Label 5</th>
							<th>Label 6</th>
							<th>Label 7</th>
							<th>Label 8</th>
							<th>Label 9</th>
						</tr>
					</thead>
					<tbody>
						<tr>
							<th>First Label</th>
							<td>48</td>
							<td>125</td>
							<td>159</td>
							<td>147</td>
							<td>154</td>
							<td>114</td>
							<td>163</td>
							<td>122</td>
							<td>96</td>
						</tr>
						<tr>
							<th>Second Label</th>
							<td>8</td>
							<td>27</td>
							<td>0</td>
							<td>79</td>
							<td>47</td>
							<td>59</td>
							<td>80</td>
							<td>30</td>
							<td>70</td>
						</tr>
						<tr>
							<th>Third Label</th>
							<td>28</td>
							<td>56</td>
							<td>98</td>
							<td>112</td>
							<td>87</td>
							<td>26</td>
							<td>38</td>
							<td>110</td>
							<td>20</td>
						</tr>
						<tr>
							<th>Fourth Label</th>
							<td>38</td>
							<td>43</td>
							<td>69</td>
							<td>54</td>
							<td>16</td>
							<td>16</td>
							<td>202</td>
							<td>20</td>
							<td>73</td>
						</tr>
					</tbody>	
				</table>
			</div>
			
		</div>
	</div>
	
	<div class="grid_12">
	
		<div class="box">
		
			<div class="header">
				<h2><?= Html::imagen("miniconos/folder_table.png","Facturas",0,0,"class: icon") ?>Estadística de Facturación</h2>
			</div>
			
			<div class="content">
				<div class="spacer"></div>
				<div class="full-stats">
					<div class="stat hlist" data-list='[{"val":17621,"format":"$0,0;-$0,0","title":"already paid","color":"green"},{"val":1125,"format":"$0,0;-$0,0","title":"not paid yet","color":"red"},{"val":18746,"format":"$0,0;-$0,0","title":"total taxes"}]' data-flexiwidth=true></div>
				</div>
				<div class="clearfix"></div>
				<div class="ui-progressbar" data-value=90 data-showtitle=percentage data-color=blue data-showvalue=true></div>
			</div>
			
			<div class="actions">
				<div class="left">
					<a href="#" class="button grey">Print invoices</a>
				</div>
				<div class="right">
					<a href="#" class="button">Generate report</a>
				</div>
			</div>
			
		</div>
	</div>
	<div class="grid_12">
		<form class="box validate">
		
			<div class="header">
				<h2><?= Html::imagen("miniconos/newspaper.png","Mensajes",0,0,"class: icon") ?>Mensajes</h2>
			</div>
			
			<div class="content">
				<div class="spacer"></div>
				<div class="messages full chat">
	
					<div class="msg reply">
						<?= Html::imagen("icons/packs/iconsweets2/25x25/user-2.png") ?>
						<div class="content">
							<h3><a href="pages_profile.html">John Doe</a> <span>says:</span><small>3 hours ago</small></h3>
							<p>Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore
							et dolore magna aliquyam erat, sed diam voluptua.</p>
						</div>
					</div>
					
					<div class="msg">
						<?= Html::imagen("icons/packs/iconsweets2/25x25/user-2.png") ?>
						<div class="content">
							<h3><a href="pages_profile.html">Peter Doe</a> <span>says:</span><small>5 hours ago</small></h3>
							<p>At vero eos et accusam et justo duo dolores et ea rebum.
							Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.</p>
						</div>
					</div>
					
				</div>
			</div>
		
			<div class="actions">
				<div class="left">
					<label for="fb_pin" class=inline >Message to John Doe:</label>
					<input type="text" class=required name=fb_pin id=fb_pin />
				</div>
				<div class="right">
					<input type="reset" value="Cancel" class="grey" />
					<input type="submit" value="Send" name=send />
				</div>
			</div>
			
		</form>
	</div>
</section>-->