<meta name="description" content="<?= PROYECTO_DESCRIPCION ?>">
<meta name="author" content="<?= AUTOR_NOMBRE ?>">
<meta http-equiv='Content-type' content='text/html; charset=<?php echo APP_CHARSET ?>' />
<meta name="viewport" content="width=device-width,initial-scale=1">
<meta name="format-detection" content="telephone=no">
<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

<meta HTTP-EQUIV="Pragma" CONTENT="no-cache">
<meta HTTP-EQUIV="Expires" CONTENT="-1">

<link rel="dns-prefetch" href="http://fonts.googleapis.com" />
<link rel="dns-prefetch" href="http://themes.googleusercontent.com" />
<link rel="dns-prefetch" href="http://ajax.googleapis.com" />
<link rel="dns-prefetch" href="http://cdnjs.cloudflare.com" />
<link rel="dns-prefetch" href="http://agorbatchev.typepad.com" />
<link rel="shortcut icon" href="<?= PROYECTO_FAVICON ?>" type="image/x-icon" />