

<?= View::partial("base/edicion") ?>

<!-- Here goes the content. -->

	<div id= "contenedor"></div>
	<fieldset>
		<legend style="font-size: 30px; text-align: center; font-style: bold; color: green">
			<?= $successMsg ?>
			<br />
			<br />
			<legend style="font-size: 25px; text-align: center; color: black;">
				Un e-mail con los datos de su cuenta ha sido enviado a su correo electrónico.
			</legend>
		</legend>
		<br />
	</fieldset>
<!-- E
	end of #content -->
