<?= stylesheet_link_tag('jquery/south-street/jquery-ui-1.8.14.custom') ?> 

<?= javascript_include_tag('jquery/jquery-1.4.2.min')."\n" ?>
<?= javascript_include_tag('jquery/jquery-ui-1.8.14.custom.min')."\n" ?>
<?= javascript_include_tag('jquery/jquery.form')."\n" ?>
<?= javascript_include_tag('jquery/jquery.metadata')."\n" ?>
<?= javascript_include_tag('jquery/jquery.validate')."\n" ?>
<?= javascript_include_tag('jquery/kumbia_jquery') ?>