<div class="grid_4">
	<form class="box grid">

		<div class="header">
			<h2>Full Width Grid</h2>
		</div>

		<div class="content">

			<div class="row">
				<p class="_100">
					<input type="text" value="100%" />
				</p>
			</div>

			<div class="row">
				<p class="_50">
					<input type="text" value="50%" />
				</p>
				<p class="_50">
					<input type="text" value="50%" />
				</p>
			</div>

			<div class="row">
				<p class="_25">
					<input type="text" value="25%" />
				</p>
				<p class="_75">
					<input type="text" value="75%" />
				</p>
			</div>

			<div class="row">
				<p class="_75">
					<input type="text" value="75%" />
				</p>
				<p class="_25">
					<input type="text" value="25%" />
				</p>
			</div>

			<div class="row">
				<p class="_25">
					<input type="text" value="25%" />
				</p>
				<p class="_25">
					<input type="text" value="25%" />
				</p>
				<p class="_25">
					<input type="text" value="25%" />
				</p>
				<p class="_25">
					<input type="text" value="25%" />
				</p>
			</div>

		</div><!-- End of .content -->

	</form><!-- End of .box -->
</div><!-- End of .grid_4 -->