<div class="grid_12">
	<form action="" class="box">

		<div class="header">
			<h2>Masked Inputs</h2>
		</div>

		<div class="content">

			<div class="row">
				<label for="f8_mi_date"> <strong>Date</strong> <small>99/99/9999</small> </label>
				<div>
					<input data-error-type=inline class="maskDate" name=f8_mi_date id=f8_mi_date type=text />
				</div>
			</div>

			<div class="row">
				<label for="f8_mi_phone"> <strong>Phone</strong> <small>(999) 999-9999</small> </label>
				<div>
					<input class="maskPhone" name=f8_mi_phone id=f8_mi_phone type=text />
				</div>
			</div>

			<div class="row">
				<label for="f8_mi_intphone"> <strong>Int. Phone</strong> <small>+33 999 999 999</small> </label>
				<div>
					<input class="maskIntPhone" name=f8_mi_intphone id=f8_mi_intphone type=text />
				</div>
			</div>

			<div class="row">
				<label for="f8_mi_tin"> <strong>Tax ID</strong> <small>99-9999999</small> </label>
				<div>
					<input class="maskTin" name=f8_mi_tin id=f8_mi_tin type=text />
				</div>
			</div>
			<div class="row">

				<label for="f8_mi_ssn"> <strong>SSN</strong> <small>999-99-9999</small> </label>
				<div>
					<input class="maskSsn" name=f8_mi_ssn id=f8_mi_ssn type=text />
				</div>
			</div>
			<div class="row">

				<label for="f8_mi_prod"> <strong>Product Key</strong> <small>a*-999-a999</small> </label>
				<div>
					<input class="maskProd" name=f8_mi_prod id=f8_mi_prod type=text />
				</div>
			</div>

			<div class="row">
				<label for="f8_mi_po"> <strong>Purchase Order</strong> <small>aaa-999-***</small> </label>
				<div>
					<input class="maskPo" name=f8_mi_po id=f8_mi_po type=text />
				</div>
			</div>

			<div class="row">
				<label for="f8_mi_perc"> <strong>Percent</strong> <small>99%</small> </label>
				<div>
					<input class="maskPct" name=f8_mi_perc id=f8_mi_perc type=text />
				</div>
			</div>
		</div><!-- End of content -->

	</form><!-- End of .box -->
</div><!-- End of .grid_12 -->