<div class="grid_4">
	<form class="box grid">

		<div class="header">
			<h2>Full Width Grid with Label</h2>
		</div>

		<div class="content">

			<div class="row">
				<p class="_100">
					<label>100%</label>
					<input type="text" />
				</p>
			</div>

			<div class="row">
				<p class="_50">
					<label>50%</label>
					<input type="text" />
				</p>
				<p class="_50">
					<label>50%</label>
					<input type="text" />
				</p>
			</div>

			<div class="row">
				<p class="_25">
					<label>25%</label>
					<input type="text" />
				</p>
				<p class="_25">
					<label>25%</label>
					<input type="text" />
				</p>
				<p class="_25">
					<label>25%</label>
					<input type="text" />
				</p>
				<p class="_25">
					<label>25%</label>
					<input type="text" />
				</p>
			</div>
		</div><!-- End of .content -->

	</form><!-- End of .box -->
</div><!-- End of .grid_4 -->