<?php
	$modulo = "Monedas";
	$seccion = $moneda ? "Modificar Moneda" : "Nueva Moneda";
?>

<?= View::partial("base/edicion") ?>
<?= Html::breadcrumbs($controller_name."/".$action_name, $modulo."/".$seccion) ?>

<!-- Here goes the content. -->
<section id="content" class="container_12 clearfix" data-sort=true>
	<?= isset($alerta) ? $alerta : "" ?>
	<h1 class="grid_12"><?= $moneda ? "Modificar Moneda" : "Nueva Moneda" ?></h1>
	<?= Formulario::inicioAjax($moneda ? $controller_name."/modificarMoneda" : $controller_name."/registrarMoneda", "contenido", false, "class: grid_12") ?>
	<?php if($moneda) echo Formulario::oculto("moneda", $moneda -> id) ?>
		<fieldset>
			<legend>
				INFORMACION DE MONEDA
			</legend>
			<div class="row">
				<p class="_25">
					<label>Nombre</label>
					<?= Formulario::mayusculas("nombre",$moneda ? $moneda -> nombre : "","class: required") ?>
				</p>
				<p class="_75">
					<label>Descripción</label>
					<?= Formulario::mayusculas("descripcion",$moneda ? $moneda -> descripcion : "","class: required") ?>
				</p>
			</div>
			<div class="row">
				<p class="_25">
					<label>Tipo de Cambio</label>
					<?= Formulario::mayusculas("cambio",$moneda ? $moneda -> tipo_cambio : "","class: required") ?>
				</p>
			</div>
		</fieldset>
		<div class="actions">
			<div class="right" style="margin: 5px;">
				<?= Formulario::submit($moneda ? "Modificar" : "Registrar") ?>
			</div>
			<div class="left" style="margin: 5px;">
				<?= Formulario::reset("Cancelar") ?>
			</div>
		</div><!-- End of .actions -->
	<?= Formulario::fin(); ?>
</section><!-- End of #content -->