<!-- Add Client Example Dialog -->
<div style="display: none;" id="dialog_add_client" title="Nuevo Ticket de Soporte">
	<?= Formulario::inicio("tickets/registrar","ticket","class: full validate") ?>
		<div class="row">
			<label for="d2_username"> <strong>Asunto</strong> </label>
			<div>
				<?= Formulario::texto("asunto","","class: required") ?>
			</div>
		</div>
		<div class="row">
			<label for="d2_email"> <strong>Mensaje</strong> </label>
			<div>
				<?= Formulario::texto("mensaje","","class: required") ?>
			</div>
		</div>
		<div class="row">
			<label for="d2_role"> <strong>Departamento</strong> </label>
			<div>
				<?php $departamentos = Departamento::reporte("id > 0"); ?>
				<?= Formulario::selectModelo("departamento",$departamentos,"nombre","id","","data-placeholder: Elige un Departamento", "style: padding-bottom: 10px") ?>
			</div>
		</div>
	</form>
	<div class="actions">
		<div class="left">
			<button class="grey cancel">
				Cancelar
			</button>
		</div>
		<div class="right">
			<button class="submit">
				Aceptar
			</button>
		</div>
	</div>
</div><!-- End if #dialog_add_client -->

<script>
	$$.ready(function() {
		$("#dialog_add_client").dialog({
			autoOpen : false,
			modal : true,
			width : 400,
			open : function() {
				$(this).parent().css('overflow', 'visible');
				$$.utils.forms.resize()
			}
		}).find('button.submit').click(function() {
			var $el = $(this).parents('.ui-dialog-content');
			if ($el.validate().form()) {
				$el.find('form')[0].reset();
				$el.dialog('close');
			}
		}).end().find('button.cancel').click(function() {
			var $el = $(this).parents('.ui-dialog-content');
			$el.find('form')[0].reset();
			$el.dialog('close');
			;
		});

		$(".open-add-client-dialog").click(function() {
			$("#dialog_add_client").dialog("open");
			return false;
		});
	}); 
</script>
<!--  End of Add Client Example Dialog -->