<!-- Message Dialog -->
<div style="display: none;" id="dialog_message" title="Mensaje desde el Administrador"></div>

<script>
	$$.ready(function() {
		$("#dialog_message").dialog({
			autoOpen : false,
			width : 500,
			modal : true
		}).find('button').click(function() {
			$(this).parents('.ui-dialog-content').dialog('close');
		});

		$(".open-message-dialog").click(function() {
			$("#dialog_message").dialog("open");
			return false;
		});
	}); 
</script>
<!-- End of Message Dialog -->