<?= Load::lib("html"); ?>
<?= Load::lib("formato"); ?>
<?= Load::lib("formulario"); ?>
<?= Html::breadcrumbs("clientes/reporte", "Clientes/Todos los Clientes") ?>

<?= View::partial("mango/tables") ?>

<?php $clientes = Cliente::reporte("id>0","id ASC",0,0,"id,rfc,nombre,calle,exterior,interior,municipio,estado"); ?>

<section id="content" class="container_12 clearfix" data-sort=true>
	<div class="grid_12">
		<div class="box">
			<div class="header">
				<h2>Clientes</h2>
			</div>

			<div class="content">

				<div class="tabletools">
					<div class="left">
						<a class="open-add-client-dialog" href="javascript:void(0);"><i class="icon-plus"></i>New Client</a>
					</div>
					<div class="right"></div>
				</div>
				<table class="dynamic styled with-prev-next" data-table-tools='{"display":true}'>
					<thead>
						<tr>
							<th>RFC</th>
							<th>Nombre</th>
							<th>Domicilio</th>
							<th>Municipio</th>
							<th>Estado</th>
						</tr>
					</thead>
					<tbody>
						<?php if($clientes) foreach($clientes as $cliente){ ?>
						<tr>
							<td><?= utf8_encode($cliente -> rfc) ?></td>
							<td><?= utf8_encode($cliente -> nombre) ?></td>
							<td><?= utf8_encode($cliente -> calle) ?> #<?= utf8_encode($cliente -> exterior) ?><?= utf8_encode($cliente -> interior) ? ", Int. ".utf8_encode($cliente -> interior) : "" ?></td>
							<td class="center"><?= utf8_encode($cliente -> municipio) ?></td>
							<td class="center"><?= utf8_encode($cliente -> estado) ?></td>
						</tr>
						<?php } ?>
					</tbody>
				</table>

			</div><!-- End of .content -->

		</div><!-- End of .box -->
	</div><!-- End of .grid_12 -->
</section><!-- End of #content -->