<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7]> <html class="no-js lt-ie9 lt-ie8 lt-ie7" lang="en"> <![endif]-->
<!--[if IE 7]>    <html class="no-js lt-ie9 lt-ie8" lang="en"> <![endif]-->
<!--[if IE 8]>    <html class="no-js lt-ie9" lang="en"> <![endif]-->
<!-- Consider adding a manifest.appcache: h5bp.com/d/Offline -->
<!--[if gt IE 8]><!--> <html class="no-js" lang="en"> <!--<![endif]-->
<html>
	<head>
		<title><?= PROYECTO_NOMBRE ?></title>
		 
		<?= View::partial("mango/metas") ?>
		<?= View::partial("mango/css") ?>
		<?= View::partial("mango/js",false,"password: ".Session::get("password")) ?>
	</head>
	<body>
		<!-- End of loading box -->
		<?= View::partial("mango/toolbar_top") ?>
		<?= View::partial("mango/header") ?>
		
		<?= View::partial("mango/dialogos/nuevo_ticket") ?>
		
		<?= View::partial("mango/dialogos/nuevo_mensaje") ?>
		
		<?= View::partial("mango/dialogos/settings") ?>
		<?= View::partial("mango/dialogos/add_client") ?>
		<?= View::partial("mango/dialogos/mensajes") ?>
		
		<!-- The container of the sidebar and content box -->
		<div role="main" id="main" class="container_12 clearfix">
			<?= View::partial("mango/toolbar") ?>
			<?= View::partial("mango/sidebar") ?>
		
			<!-- Here goes the content. -->
			<div id="contenido" style="min-height: 400px;"><?= View::content(); ?></div>
			<!-- End of #content -->
		
		</div><!-- End of #main -->
		
		<?= View::partial("mango/footer") ?>
		
		<!-- Spawn $$.loaded -->
		<script>$$.loaded();</script>
		
		<script type="text/javascript">
			$(document).ready(function(){ 
				$("html, body").animate({ scrollTop: 0 }, 600);
			});
		</script>
		
		<!-- Prompt IE 6 users to install Chrome Frame. Remove this if you want to support IE 6.
		chromium.org/developers/how-tos/chrome-frame-getting-started -->
		<!--[if lt IE 7 ]>
		<script defer src="http://ajax.googleapis.com/ajax/libs/chrome-frame/1.0.3/CFInstall.min.js"></script>
		<script defer>window.attachEvent('onload',function(){CFInstall.check({mode:'overlay'})})</script>
		<![endif]-->
		
	</body>
</html>