<!doctype html>
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7]> <html class="no-js lt-ie9 lt-ie8 lt-ie7" lang="en"> <![endif]-->
<!--[if IE 7]>    <html class="no-js lt-ie9 lt-ie8" lang="en"> <![endif]-->
<!--[if IE 8]>    <html class="no-js lt-ie9" lang="en"> <![endif]-->

<!-- Consider adding a manifest.appcache: h5bp.com/d/Offline -->
<!--[if gt IE 8]><!--> <html class="no-js" lang="en"> <!--<![endif]-->
<head>
	<title><?= PROYECTO_NOMBRE ?></title>
		 
	<?= View::partial("mango/metas") ?>
	<?= View::partial("mango/css"); ?>
	<?= View::partial("mango/loginjs"); ?>
	
	<?= Load::lib("html"); ?>
	<?= Load::lib("formato"); ?>
	<?= Load::lib("formulario"); ?>
</head>

<body class=login>

	<!-- Some dialogs etc. -->

	<!-- The loading box -->
	<div id="loading-overlay"></div>
	<div id="loading">
		<span>Cargando...</span>
	</div>
	<!-- End of loading box -->
	
	<!--------------------------------->
	<!-- Now, the page itself begins -->
	<!--------------------------------->
	
	<!-- The toolbar at the top -->
	<section id="toolbar">
		<div class="container_12">
		
			<!-- Left side -->
			<!--<div class="left">
				<ul class="breadcrumb">
					<li><?= Html::link(APLICACION_URL, "Emisión Fiscal") ?></li>
					<li><?= Html::link(APLICACION_URL."clientes", "Clientes") ?></li>
					<li><?= Html::link(APLICACION_URL."clientes", "Inicio de Sesión") ?></li>
				</ul>
			</div>-->
			<!-- End of .left -->
			
			<!-- Right side -->
			<div class="right">
				<ul>
					<li><?= Html::link("http://www.emisionfiscal.com.mx", '<span class="icon i14_bended-arrow-left"></span>www.emisionfiscal.com.mx') ?></li>
					<li class="red"><?= Html::link("http://www.emisionfiscal.com/mx/index.php/contacto", "contratar", "Contratar") ?></li>
				</ul>
			</div><!-- End of .right -->
			
			<!-- Phone only items -->
			<div class="phone">
				
				<!-- User Link -->
				<li><a href="#"><span class="icon icon-home"></span></a></li>
				<!-- Navigation -->
				<li><a href="#"><span class="icon icon-heart"></span></a></li>
			
			</div><!-- End of .phone -->
			
		</div><!-- End of .container_12 -->
	</section><!-- End of #toolbar -->
	
	<!-- The header containing the logo -->
	<header class="container_12">
		
		<div class="container">
		
			<!-- Your logos -->
			<?= Html::link(APLICACION_URL, Html::imagen("logo.png","Emision Fiscal",210)) ?>
			
			<!-- Right link -->
			<div class="right">
				<span style="color:black; text-shadow: none;">¿No eres usuario?</span>
				<?= Html::link("http://www.emisionfiscal.com/mx/index.php/planes", "¡Contratanos!") ?>
			</div>
			
		</div><!-- End of .container -->
	
	</header><!-- End of header -->
	
	<span id="main"><?= View::content() ?></span	>
	
	<!-- Spawn $$.loaded -->
	<script>
		$$.loaded();
	</script>
	
	<!-- Prompt IE 6 users to install Chrome Frame. Remove this if you want to support IE 6.
	   chromium.org/developers/how-tos/chrome-frame-getting-started -->
	<!--[if lt IE 7 ]>
	<script defer src="http://ajax.googleapis.com/ajax/libs/chrome-frame/1.0.3/CFInstall.min.js"></script>
	<script defer>window.attachEvent('onload',function(){CFInstall.check({mode:'overlay'})})</script>
	<![endif]-->

</body>
</html>