<?php
	$modulo = "Paquetes";
	$seccion = $paquete ? "Modificar Paquete" : "Nuevo Paquete";
?>

<?= View::partial("base/edicion") ?>
<?= Html::breadcrumbs($controller_name."/".$action_name, $modulo."/".$seccion) ?>

<!-- Here goes the content. -->
<section id="content" class="container_12 clearfix" data-sort=true>
	<?= isset($alerta) ? $alerta : "" ?>
	<h1 class="grid_12"><?= $paquete ? "Modificar Paquete" : "Nuevo Paquete" ?></h1>
	<?= Formulario::inicioAjax($paquete ? $controller_name."/modificar" : $controller_name."/registrar", "contenido", false, "class: grid_12") ?>
	<?php if($paquete) echo Formulario::oculto("paquete", $paquete -> id) ?>
		<fieldset>
			<legend>
				INFORMACIÓN DE PAQUETE
			</legend>
			<div class="row">
				<p class="_50">
					<label>Nombre</label>
					<?= Formulario::mayusculas("nombre", $paquete ? $paquete -> nombre: "") ?>
				</p>
				<p class="_25">
					<label>Tipo</label>
					<?= Formulario::select("tipo",array("CBB" => "CBB","CFD" => "CFD","CFDI" => "CFDI"),$paquete ? $paquete -> tipo  : "CBB","data-placeholder: Selecciona Tipo") ?>
				</p>
				<p class="_25">
					<label>Activo</label>
					<?= Formulario::select("activo",array("SI" => "SI","NO" => "NO"),$paquete ? $paquete -> activo  : "NO","class: search required","data-placeholder: Activo?") ?>
				</p>
			</div>
			<div class="row">
				<p class="_25">
					<label>Facturas Incluidas</label>
					<?= Formulario::numerico("facturas_incluidas",$paquete ? $paquete -> facturas_incluidas : "") ?>
				</p>
				<p class="_25">
					<label>Costo Factura Adicional</label>
					<?= Formulario::dinero("costo_factura_adicional", $paquete ? $paquete -> costo_factura_adicional : "") ?>
				</p>
				<p class="_25">
					<label>Número de Usuarios</label>
					<?= Formulario::numerico("usuarios", $paquete ? $paquete -> usuarios : "") ?>
				</p> 
				<p class="_25">
					<label>Almacenamiento (MB)</label>
					<?= Formulario::numerico("almacenamiento",$paquete ? $paquete -> almacenamiento : "") ?>
				</p>
			</div>
			<div class="row">
				<p class="_25">
					<label>Multiple Moneda</label>
					<?= Formulario::select("multiple_moneda",array("SI" => "SI","NO" => "NO"),$paquete ? $paquete -> multiple_moneda  : "NO","class: search required","data-placeholder: Multiple Moneda?") ?>
				</p>
				<p class="_25">
					<label>Multiple Sucursal</label>
					<?= Formulario::select("multiple_sucursal",array("SI" => "SI","NO" => "NO"),$paquete ? $paquete -> multiple_sucursal  : "NO","class: search required","data-placeholder: Multiple Sucursal") ?>
				</p>
				<p class="_25">
					<label>Costo Mensual</label>
					<?= Formulario::dinero("costo_mensual", $paquete ? $paquete -> costo_mensual : "") ?>
				</p>
				<p class="_25">
					<label>Costo Anual</label>
					<?= Formulario::dinero("costo_anual", $paquete ? $paquete -> costo_anual : "") ?>
				</p> 
			</div>
			<div class="row">
				<p class="_25">
					<label>Soporte Online</label>
					<?= Formulario::select("soporte_online",array("SI" => "SI","NO" => "NO"),$paquete ? $paquete -> soporte_online  : "SI","class: search required","data-placeholder: Soporte Activo?") ?>
				</p>
				<p class="_25">
					<label>Soporte Chat</label>
					<?= Formulario::select("soporte_chat",array("SI" => "SI","NO" => "NO"),$paquete ? $paquete -> soporte_chat  : "NO","class: search required","data-placeholder: Soporte Activo?") ?>
				</p>
				<p class="_25">
					<label>Soporte Telefono</label>
					<?= Formulario::select("soporte_telefono",array("SI" => "SI","NO" => "NO"),$paquete ? $paquete -> soporte_telefono  : "NO","class: search required","data-placeholder: Soporte Activo?") ?>
				</p> 
				<p class="_25">
					<label>Vigencia</label>
					<?= Formulario::fecha("vigencia",$paquete ? $paquete -> vigencia : date("d/m/Y", mktime(0,0,0,12,31,date("Y")))) ?>
				</p>
			</div>
		</fieldset>
		</fieldset>
		<div class="actions">
			<div class="right" style="margin: 5px;">
				<?= Formulario::submit($paquete ? "Modificar" : "Registrar") ?>
			</div>
			<div class="left" style="margin: 5px;">
				<?= Html::linkAjax("paquetes/reporte","Regresar","contenido","class: button red"); ?>
			</div>
		</div><!-- End of .actions -->
	<?= Formulario::fin(); ?>
</section><!-- End of #content -->