<?php
	$modulo = "Paquetes";
	$seccion = "Reporte Paquetes"; 

	$campos = array("id","nombre","tipo","vigencia","activo","costo_mensual","costo_anual");
	$orden = "id ASC";
	$cantidad = 100;
	$filtro = Session::get("filtro") ? Session::get("filtro") : "id>0";
	
	$paquetes = Paquete::reporte($filtro,$orden,0,$cantidad,$campos);
?>

<?= View::partial("base/reporte") ?>
<?= Html::breadcrumbs($controller_name."/".$action_name, $modulo."/".$seccion) ?>

<script>
	function enviarFormulario(){
		var parametros = "0";
		
		$("input:checkbox:checked").each(function(){
			if($(this).attr("name")!="muestra"){
				var elemento = $(this).attr("name").split('_');
				parametros+="|"+elemento[1];  
			} 
		});
		
		if(parametros != "0"){
			event.preventDefault();
			
			if(confirm('¿Estas seguro que deseas eliminar los registros seleccionados?')){
				$('#contenido').load('<?= PROYECTO_BASE.$controller_name ?>/eliminarSeleccionados/'+parametros);		
			}
			else{
				return false;
			}
		}
	}
</script>
<section id="content" class="container_12 clearfix" data-sort=true>
	<?= isset($alerta) ? $alerta : "" ?>
	<div class="grid_12">
		<div class="box">
			<div class="header">
				<h2><?= "PAQUETES" ?></h2>
			</div>
			<div class="content">
				<div class="tabletools">
					<div class="left">
						<a class="open-add-client-dialog" href="javascript:void(0);" onclick="enviarFormulario()">Eliminar</a>
					</div>
					<div class="right">
						<!-- LINKS PARA LOS FILTROS -->
						<?= Html::linkAjax($controller_name."/".$action_name."/activos", 'Activos', "contenido","title: Filtrar Activos") ?>
						<?= Html::linkAjax($controller_name."/".$action_name."/inactivos", 'Inactivos', "contenido","title: Filtrar Inactivos") ?>
						<?= Html::linkAjax($controller_name."/".$action_name."/vigentes", 'Vigentes', "contenido","title: Filtrar Vigentes") ?>
						<?= Html::linkAjax($controller_name."/".$action_name."/cbb", 'CBB', "contenido","title: Filtrar CBB") ?>
						<?= Html::linkAjax($controller_name."/".$action_name."/cfd", 'CFD', "contenido","title: Filtrar CFD") ?>
						<?= Html::linkAjax($controller_name."/".$action_name."/cfdi", 'CFDI', "contenido","title: Filtrar CFDI") ?>
					</div>
				</div>
				<table id="tabla" class="dynamic styled with-prev-next" data-table-tools='{"display":false}'>
					<thead>
						<!-- ENCABEZADOS DE LA TABLA -->
						<tr>
							<td>
								<input type="checkbox" name="muestra" onchange="$(this).parents('table').find(':checkbox').attr('checked', $(this).attr('checked') || false)">
							</td>
							<th>Nombre</th>
							<th>Tipo</th>
							<th>Costo Mensual</th>
							<th>Costo Anual</th>
							<th>Vigencia</th>
							<th>Activo</th>
							<td class="center" style="font-weight: bold;">Acciones</td>
						</tr>
					</thead>
					<tbody>
						<!-- REGISTROS DE LA TABLA -->
						<?php if($paquetes) foreach($paquetes as $paquete){ ?>
						<tr>
							<td>
								<?= Formulario::checkbox("registro_".$paquete -> id."") ?>
							</td>
							<td align="center"><?= $paquete -> nombre ?></td>
							<td align="center"><?= $paquete -> tipo ?></td>
							<td align="center"><?= Formato::dinero($paquete -> costo_mensual) ?></td>
							<td align="center"><?= Formato::dinero($paquete -> costo_anual) ?></td>
							<td align="center"><?= Formato::fecha($paquete -> vigencia) ?></td>
							<td align="center"><?= $paquete -> activo ?></td>
							<td style="width: 45px;">
								<?= Html::linkAjax($controller_name."/consulta/".$paquete -> id, '<i class="icon-pencil"></i>', "contenido","class: button small grey tooltip","data-gravity: s","title: Editar") ?>
								<?= Html::linkAjaxConfirmado($controller_name."/eliminar/".$paquete -> id, '<i class="icon-remove"></i>', "contenido","class: button small grey tooltip","data-gravity: s","title: Eliminar") ?>
							</td>
						</tr>
						<?php } ?>
					</tbody>
				</table>
			</div>
		</div>
	</div>
</section>