<?php
	$modulo = "Configuración";
	$seccion = "Modificar Contribuyente";
?>

<?= View::partial("base/edicion") ?>
<?= Html::breadcrumbs($controller_name."/".$action_name, $modulo."/".$seccion) ?>
<!-- Here goes the content. -->
<script>
	function stopUpload(x){
		
		switch(x){
			case -11: 	document.getElementById('alerta').innerHTML = '<div class="alert error"><span class="icon"></span><span class="close">x</span>El Campo <b style="font-weight: bold;">RFC</b> es <b style="font-weight: bold;">OBLIGATORIO</b>.</div>';
						break;
			case -12: 	document.getElementById('alerta').innerHTML = '<div class="alert error"><span class="icon"></span><span class="close">x</span>El Campo <b style="font-weight: bold;">NOMBRE</b> es <b style="font-weight: bold;">OBLIGATORIO</b>.</div>';
						break;
			case -13: 	document.getElementById('alerta').innerHTML = '<div class="alert error"><span class="icon"></span><span class="close">x</span>El Campo <b style="font-weight: bold;">CALLE</b> es <b style="font-weight: bold;">OBLIGATORIO</b>.</div>';
						break;
			case -14: 	document.getElementById('alerta').innerHTML = '<div class="alert error"><span class="icon"></span><span class="close">x</span>El Campo <b style="font-weight: bold;">NO. EXTERIOR</b> es <b style="font-weight: bold;">OBLIGATORIO</b>.</div>';
						break;
			case -15: 	document.getElementById('alerta').innerHTML = '<div class="alert error"><span class="icon"></span><span class="close">x</span>El Campo <b style="font-weight: bold;">MUNICIPIO</b> es <b style="font-weight: bold;">OBLIGATORIO</b>.</div>';
						break;
			case -16: 	document.getElementById('alerta').innerHTML = '<div class="alert error"><span class="icon"></span><span class="close">x</span>El Campo <b style="font-weight: bold;">ESTADO</b> es <b style="font-weight: bold;">OBLIGATORIO</b>.</div>';
						break;
			case -17: 	document.getElementById('alerta').innerHTML = '<div class="alert error"><span class="icon"></span><span class="close">x</span>El Campo <b style="font-weight: bold;">PAIS</b> es <b style="font-weight: bold;">OBLIGATORIO</b>.</div>';
						break;
		}
		
		if(x == -3){
	    	document.getElementById('alerta').innerHTML = '<div class="alert error"><span class="icon"></span><span class="close">x</span>La Cedula debe ser una imagen con extensión <b style="font-weight: bold;">JPG / PNG / GIF</b>.</div>';
	    }
	    
	    if(x == -2){
	    	document.getElementById('alerta').innerHTML = '<div class="alert error"><span class="icon"></span><span class="close">x</span>El Logotipo debe ser una imagen con extensión <b style="font-weight: bold;">JPG / PNG / GIF</b>.</div>';
	    }
	    
	    if(x == -1){
	    	document.getElementById('alerta').innerHTML = '<div class="alert error"><span class="icon"></span><span class="close">x</span>El Contribuyente buscado no fue encontrado en la Base de Datos.</div>';
	    }
		
		if(x == 0){
	    	document.getElementById('alerta').innerHTML = '<div class="alert success"><span class="icon"></span><span class="close">x</span>El Contribuyente ha sido ACTUALIZADO correctamente.</div>';
	    }
	    
	    if(x == 1){
	    	document.getElementById('alerta').innerHTML = '<div class="alert warning"><span class="icon"></span><span class="close">x</span>Los campos han sido ACTUALIZADOS, pero recuerda que necesitas cargar tu <b style="font-weight: bold;">Cedula Fiscal</b>, para el Formato de Impresión</div>';
	    }
	    
	    if(x == 2){
	    	document.getElementById('alerta').innerHTML = '<div class="alert warning"><span class="icon"></span><span class="close">x</span>Los campos han sido ACTUALIZADOS, pero recuerda que necesitas cargar tu <b style="font-weight: bold;">Logotipo</b>, para el Formato de Impresión</div>';
	    }
		
	    return true;   
	}
</script>
<section id="content" class="container_12 clearfix" data-sort=true>
	<?= isset($alerta) ? $alerta : "" ?>
	<span id="alerta" class="grid_12"></span>
	<h1 class="grid_12"><?= "Modificar Contribuyente"?></h1>
	<?= Formulario::inicio($controller_name."/modificarContribuyente", false, "class: grid_12", "target: upload_target") ?>
	<?php if($contribuyente) echo Formulario::oculto("contribuyente", $contribuyente -> id) ?>
		<fieldset>
			<legend>
				INFORMACIÓN DEL CONTRIBUYENTE
			</legend>
			<div class="row">
				<p class="_25">
					<label>RFC</label>
					<?= Formulario::rfc("rfc", $contribuyente ? $contribuyente -> rfc : "","class: required","minlength: 12","maxlength: 13") ?>
				</p>
				<p class="_50">
					<label>Nombre o Razón Social</label>
					<?= Formulario::mayusculas("nombre",$contribuyente ? $contribuyente -> nombre : "","class: required") ?>
				</p> 
				<p class="_25">
					<label>Nombre Comercial</label>
					<?= Formulario::mayusculas("nombre_comercial",$contribuyente ? $contribuyente -> nombre_comercial : "","class: required") ?>
				</p>
			</div>
			<div class="row">
				<p class="_50">
					<label>Cedula Fiscal</label>
					<?= Formulario::archivo("cedula","","class: required") ?>
				</p>
				<p class="_50">
					<label>Logotipo</label>
					<?= Formulario::archivo("logotipo","","class: required") ?>
				</p>
			</div>
		</fieldset>
		<fieldset>
			<legend>
				DOMICILIO FISCAL
			</legend>
			<div class="row">
				<p class="_50">
					<label>Calle</label>
					<?= Formulario::mayusculas("calle",$contribuyente ? $contribuyente -> calle : "","class: required") ?>
				</p>
				<p class="_25">
					<label>No. Exterior</label>
					<?= Formulario::mayusculas("exterior",$contribuyente ? $contribuyente -> exterior : "","class: required") ?>
				</p>
				<p class="_25">
					<label>No. Interior</label>
					<?= Formulario::mayusculas("interior",$contribuyente ? $contribuyente -> interior : "") ?>
				</p>
			</div>
			<div class="row">
				<p class="_50">
					<label>Colonia</label>
					<?= Formulario::mayusculas("colonia",$contribuyente ? $contribuyente -> colonia : "") ?>
				</p>
				<p class="_25">
					<label>Localidad</label>
					<?= Formulario::mayusculas("localidad",$contribuyente ? $contribuyente -> localidad : "") ?>
				</p>
				<p class="_25">
					<label>Código Postal</label>
					<?= Formulario::numerico("cpostal",$contribuyente ? $contribuyente -> cpostal : "","class: required digits","minlength: 5", "maxlength: 5") ?>
				</p>
			</div>
			<div class="row">
				<p class="_50">
					<label>Municipio</label>
					<?= Formulario::mayusculas("municipio",$contribuyente ? $contribuyente -> municipio : "","class: required") ?>
				</p>
				<p class="_25">
					<label>Estado</label>
					<?= Formulario::selectEstados("estado",$contribuyente ? $contribuyente -> estado  : "","class: required search","data-placeholder: Selecciona Estado") ?>
				</p>
				<p class="_25">
					<label>País</label>
					<?= Formulario::select("pais",array("","MÉXICO" => "MÉXICO"),$contribuyente ? $contribuyente -> pais : "","class: required search","data-placeholder: Selecciona País") ?>
				</p>
			</div>
		</fieldset>
		<fieldset>
			<legend>
				INFORMACIÓN DE CONTACTO
			</legend>
			<div class="row">
				<p class="_25">
					<label>Teléfono</label>
					<?= Formulario::numerico("telefono",$contribuyente ? $contribuyente -> telefono : "","class: maskPhone") ?>
				</p>
				<p class="_25">
					<label>Celular</label>
					<?= Formulario::numerico("celular",$contribuyente ? $contribuyente -> celular : "","class: maskPhone") ?>
				</p>
				<p class="_50">
					<label>Correo Electrónico</label>
					<?= Formulario::texto("correo",$contribuyente ? $contribuyente -> correo : "","class: email") ?>
				</p>
			</div>
		</fieldset>
		<div class="actions">
			<div class="right" style="margin: 5px;">
				<?= Formulario::submit("Modificar") ?>
			</div>
			<div class="left" style="margin: 5px;">
				<?= Formulario::reset("Cancelar") ?>
			</div>
		</div><!-- End of .actions -->
	<?= Formulario::fin(); ?>
</section><!-- End of #content -->
<iframe id="upload_target" name="upload_target" src="#" style="width:0;height:0;border:0px solid #fff;"></iframe>
