<?= Load::lib("html") ?>
<section id="content" class="container_12 clearfix" data-sort=true>
	<div class="grid_12">
		<form class="box validate">
		
			<div class="header">
				<h2><?= Html::imagen("miniconos/newspaper.png","Mensajes",0,0,"class: icon") ?>Mensajes</h2>
			</div>
			
			<div class="content">
				<div class="spacer"></div>
				<div class="messages full chat">
	
					<div class="msg reply">
						<?= Html::imagen("icons/packs/iconsweets2/25x25/user-2.png") ?>
						<div class="content">
							<h3><a href="pages_profile.html">John Doe</a> <span>says:</span><small>3 hours ago</small></h3>
							<p>Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore
							et dolore magna aliquyam erat, sed diam voluptua.</p>
						</div>
					</div>
					
					<div class="msg">
						<?= Html::imagen("icons/packs/iconsweets2/25x25/user-2.png") ?>
						<div class="content">
							<h3><a href="pages_profile.html">Peter Doe</a> <span>says:</span><small>5 hours ago</small></h3>
							<p>At vero eos et accusam et justo duo dolores et ea rebum.
							Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.</p>
						</div>
					</div>
					
				</div>
			</div><!-- End of .content -->
			
			<div class="actions">
				<div class="left">
					<input type="text" class=required name=fb_pin id=fb_pin style="width: 300px;" />
				</div>
				<div class="right">
					<input type="reset" value="Cancel" class="grey" />
					<input type="submit" value="Send" name=send />
				</div>
			</div><!-- End of .actions -->
			
		</form><!-- End of .box -->
	</div>
</section>