<?= Load::lib("html"); ?>
<?= Load::lib("formato"); ?>
<?= Load::lib("formulario"); ?>

﻿<h1 class="grid_12">TITULO DE LA SECCION</h1>

<?= View::partial("mango/demos/formularios/form1") ?>
<?= View::partial("mango/demos/formularios/form2") ?>
<?= View::partial("mango/demos/formularios/form3") ?>
<?= View::partial("mango/demos/formularios/form4") ?>
<?= View::partial("mango/demos/formularios/form5") ?>
<?= View::partial("mango/demos/formularios/form6") ?>