<?php
	$modulo = "Usuarios";
	$seccion = "Todos los Usuarios"; 

	$campos = array("id","nombres","apellidos","correo","usuario");
	$orden = "id ASC";
	$cantidad = 100;
	$filtro = Session::get("filtro");
	
	$usuarios = usuario::reporte($filtro,$orden,0,$cantidad,$campos);
?>

<?= View::partial("base/reporte") ?>
<?= Html::breadcrumbs($controller_name."/".$action_name, $modulo."/".$seccion) ?>

<script>
	function enviarFormulario(){
		var parametros = "0";
		
		$("input:checkbox:checked").each(function(){
			if($(this).attr("name")!="muestra"){
				var elemento = $(this).attr("name").split('_');
				parametros+="|"+elemento[1];  
			} 
		});
		
		if(parametros != "0"){
			event.preventDefault();
			
			if(confirm('¿Estas seguro que deseas eliminar los registros seleccionados?')){
				$('#contenido').load('<?= PROYECTO_BASE.$controller_name ?>/eliminarSeleccionados/'+parametros);		
			}
			else{
				return false;
			}
		}
	}
</script>
<section id="content" class="container_12 clearfix" data-sort=true>
	<?= isset($alerta) ? $alerta : "" ?>
	<div class="right" style="margin: 9px;">
		<?= Formulario::inicioAjax("usuarios/registro", "contenido", false, "class: grid_12") ?>
			<?= Formulario::submit("Agregar Nuevo","style: float: right") ?>
		<?= Formulario::fin() ?>
		<br><br>
	</div>
	<div class="grid_12">
		<div class="box">
			<div class="header">
				<h2><?= "USUARIOS" ?></h2>
			</div>
			<div class="content">
				<div class="tabletools">
					<div class="left">
						<a class="open-add-client-dialog" href="javascript:void(0);" onclick="enviarFormulario()">Eliminar</a>
					</div>
					<div class="right">
					</div>
				</div>
				<table id="tabla" class="dynamic styled with-prev-next" data-table-tools='{"display":false}'>
					<thead>
						<!-- ENCABEZADOS DE LA TABLA -->
						<tr>
							<td>
								<input type="checkbox" name="muestra" onchange="$(this).parents('table').find(':checkbox').attr('checked', $(this).attr('checked') || false)">
							</td>
							<th>Nombre Completo</th>
							<th>Correo Electrónico</th>
							<th>Usuario</th>
							<td class="center" style="font-weight: bold;">Acciones</td>
						</tr>
					</thead>
					<tbody>
						<!-- REGISTROS DE LA TABLA -->
						<?php if($usuarios) foreach($usuarios as $usuario){ ?>
						<tr>
							<td>
								<?= Formulario::checkbox("registro_".$usuario -> id."") ?>
							</td>
							<td class="center"><?= $usuario -> nombres ?></td>
							<td class="center"><?= $usuario -> correo ?></td>
							<td class="center"><?= $usuario -> usuario ?></td>
							<td style="width: 45px;">
								<?= Html::linkAjax($controller_name."/consulta/".$usuario -> id, '<i class="icon-pencil"></i>', "contenido","class: button small grey tooltip","data-gravity: s","title: Editar") ?>
								<?= Html::linkAjaxConfirmado($controller_name."/eliminar/".$usuario -> id, '<i class="icon-remove"></i>', "contenido","class: button small grey tooltip","data-gravity: s","title: Eliminar") ?>
							</td>
						</tr>
						<?php } ?>
					</tbody>
				</table>
			</div>
		</div>
	</div>
</section>