<?= Load::lib("html") ?>
<?= Load::lib("formulario") ?>
<?= View::partial("base/reporte") ?>
<?= View::partial("base/edicion") ?>

<?= $factura ? "" : Formulario::inicioAjax($controller_name."/agregarManual", "contenido", false, "class: grid_12", "style: margin-bottom: 10px;") ?>
<?php if($factura) echo Formulario::oculto("factura", $factura -> id) ?>
	<fieldset>
		<legend>
			AGREGAR CONCEPTO
			<span style="float: right;">
				<?= Html::linkAjax($controller_name."/conceptos/automatico/".$permiso_facturar,"BUSQUEDA","conceptos") ?>
			</span>
		</legend>
		<div class="row">
			<p class="_25">
				<label>Cantidad</label>
				<?= Formulario::numerico("cantidad","","class: required","placeholder: 1.00") ?>
			</p>
			<p class="_25">
				<label>Unidad</label>
				<?= Formulario::selectModelo("unidad", $unidades,"nombre","id","","class: required search","data-placeholder: Unidad") ?>
			</p>
			<p class="_25">
				<label>Producto o Servicio</label>
				<?= Formulario::mayusculas("concepto","","class: required","placeholder: Descripcion") ?>
			</p>
			<p class="_25">
				<label>Precio Unitario</label>
				<?= Formulario::numerico("precio","","class: required","placeholder: 1.00") ?>
			</p>
		</div>
	</fieldset>
	<div class="actions">
		<div class="right" style="margin: 5px;">
			<?= $permiso_facturar==0 ? "" : Formulario::submit("Agregar Concepto") ?>
		</div>
		<div class="left" style="margin: 5px;">
		</div>
	</div><!-- End of .actions -->
<?= Formulario::fin(); ?>