<?php
	$modulo = "Impuestos";
	$seccion = $impuesto ? "Modificar Impuesto" : "Nuevo Impuesto";
?>

<?= View::partial("base/edicion") ?>
<?= Html::breadcrumbs($controller_name."/".$action_name, $modulo."/".$seccion) ?>

<!-- Here goes the content. -->
<section id="content" class="container_12 clearfix" data-sort=true>
	<?= isset($alerta) ? $alerta : "" ?>
	<h1 class="grid_12"><?= $impuesto ? "Modificar Impuesto" : "Nuevo Impuesto" ?></h1>
	<?= Formulario::inicioAjax($impuesto ? $controller_name."/modificarImpuesto" : $controller_name."/registrarImpuesto", "contenido", false, "class: grid_12") ?>
	<?php if($impuesto) echo Formulario::oculto("impuesto", $impuesto -> id) ?>
		<fieldset>
			<legend>
				INFORMACION DE IMPUESTO
			</legend>
			<div class="row">
				<p class="_25">
					<label>Nombre</label>
					<?= Formulario::mayusculas("nombre",$impuesto ? $impuesto -> nombre : "","class: required") ?>
				</p>
				<p class="_75">
					<label>Descripción</label>
					<?= Formulario::mayusculas("descripcion",$impuesto ? $impuesto -> descripcion : "","class: required") ?>
				</p>
			</div>
			<div class="row">
				<p class="_25">
					<label>Tasa</label>
					<?= Formulario::numerico("tasa",$impuesto ? $impuesto -> tasa : "","class: required") ?>
				</p>
				<p class="_25">
					<label>Tipo</label>
					<?php $tipos = array("TRASLADADO"=>"TRASLADADO","RETENIDO"=>"RETENIDO")?>
					<?= Formulario::select("tipo",$tipos,$impuesto ? $impuesto -> tipo : "TRASLADADO","class: required") ?>
				</p>
			</div>
		</fieldset>
		<div class="actions">
			<div class="right" style="margin: 5px;">
				<?= Formulario::submit($impuesto ? "Modificar" : "Registrar") ?>
			</div>
			<div class="left" style="margin: 5px;">
				<?= Formulario::reset("Cancelar") ?>
			</div>
		</div><!-- End of .actions -->
	<?= Formulario::fin(); ?>
</section><!-- End of #content -->