<?php
	$modulo = "Facturación";
	$seccion = "Nueva Factura";
?>

<?= View::partial("base/reporte") ?>
<?= View::partial("base/edicion") ?>
<?= Html::breadcrumbs($controller_name."/".$action_name, $modulo."/".$seccion) ?>

<!-- Here goes the content. -->
<section id="content" class="container_12 clearfix" data-sort=true>
	<?= isset($alerta) ? $alerta : "" ?>
	<h1 class="grid_12"><?= $factura ? "Información Factura" : "Nueva Factura" ?></h1>
	<?= Formulario::inicioAjax($factura ? $controller_name."/modificar" : $controller_name."/registrar", "contenido", false, "class: grid_12") ?>
	<?php if($factura) echo Formulario::oculto("factura", $factura -> id) ?>
		<fieldset>
			<legend>
				INFORMACIÓN DE LA FACTURA
			</legend>
			<div class="row">
				<p class="_50">
					<label>Cliente (Receptor)</label>
					<?= Formulario::selectModeloClientes("cliente", $clientes,"nombre","id","","class: required search","data-placeholder: Selecciona Cliente") ?>
				</p>
				<p class="_25">
					<label>Nombre o Razón Social</label>
					<?= Formulario::fecha("fecha",date("d/m/Y"),"dd/mm/yy",false,0,"class: required") ?>
				</p> 
				<p class="_25">
					<label><?= $sucursales ? "Sucursal" : "Serie / Folio" ?></label>
					<?php
						if($sucursales){
							echo Formulario::selectModelo("sucursal",$sucursales,"nombre","id", $factura ? $factura -> sucursal_id : $matrix,"class: search","data-placeholder: Selecciona Sucursal");
						}
						else{
							echo Formulario::selectModelo("serie",$series,"serie","id", $factura ? $factura -> cbb_folios_id : $xerie,"class: required search","data-placeholder: Selecciona Serie");
						}
					?>
				</p>
			</div>
		</fieldset>
		<div class="actions">
			<div class="right" style="margin: 5px;">
				<?= $factura ? "" : Formulario::submit("Crear Factura") ?>
			</div>
			<div class="left" style="margin: 5px;">
			</div>
		</div><!-- End of .actions -->
	<?= Formulario::fin(); ?>
	<div class="grid_12">
		<div class="box">
			<div class="header">
				<h2><?= "CONCEPTOS" ?></h2>
			</div>
			<div class="content">
				<table id="tabla" class="dynamic styled with-prev-next" data-table-tools='{"display":false}'>
					<thead>
						<!-- ENCABEZADOS DE LA TABLA -->
						<tr>
							<!--
							<td>
								<input type="checkbox" name="muestra" onchange="$(this).parents('table').find(':checkbox').attr('checked', $(this).attr('checked') || false)">
							</td>
							-->
							<th>RFC</th>
							<th>Nombre</th>
							<th>Domicilio</th>
							<th>Municipio</th>
							<th>Estado</th>
							<td class="center" style="font-weight: bold;"></td>
						</tr>
					</thead>
					<tbody>
						<!-- REGISTROS DE LA TABLA -->
						<?php if($clientes) foreach($clientes as $cliente){ ?>
						<tr>
							<!--
							<td>
								<?= Formulario::checkbox("registro_".$cliente -> id."") ?>
							</td>
							-->
							<td><?= $cliente -> rfc ?></td>
							<td><?= $cliente -> nombre ?></td>
							<td><?= $cliente -> calle ?> #<?= $cliente -> exterior ?><?= $cliente -> interior ? ", Int. ".$cliente -> interior : "" ?></td>
							<td class="center"><?= $cliente -> municipio ?></td>
							<td class="center"><?= $cliente -> estado ?></td>
							<td style="width: 15px;">
								<!--
								<?= Html::linkAjax($controller_name."/consulta/".$cliente -> id, '<i class="icon-pencil"></i>', "contenido","class: button small grey tooltip","data-gravity: s","title: Editar") ?>
								-->
								<?= Html::linkAjaxConfirmado($controller_name."/eliminar/".$cliente -> id, '<i class="icon-remove"></i>', "contenido","class: button small grey tooltip","data-gravity: s","title: Eliminar") ?>
							</td>
						</tr>
						<?php } ?>
					</tbody>
				</table>
			</div>
		</div>
	</div>
	<?= $factura ? "" : Formulario::inicioAjax($controller_name."/agregar", "contenido", false, "class: grid_12") ?>
	<?php if($factura) echo Formulario::oculto("factura", $factura -> id) ?>
		<fieldset>
			<legend>
				AGREGAR CONCEPTO
			</legend>
			<div class="row">
				<p class="_25">
					<label>Cantidad</label>
					<?= Formulario::numerico("cantidad","1.00","class: required") ?>
				</p> 
				<p class="_50">
					<label>Producto o Servicio</label>
					<?= Formulario::selectModelo("producto", $productos,"nombre","id","","class: required search","data-placeholder: Selecciona Producto o Servicio") ?>
				</p>
				<p class="_25">
					<label>Precio Unitario</label>
					<?= Formulario::numerico("precio","1.00","class: required") ?>
				</p> 
			</div>
		</fieldset>
		<div class="actions">
			<div class="right" style="margin: 5px;">
				<?= $factura ? "" : Formulario::submit("Agregar Concepto") ?>
			</div>
			<div class="left" style="margin: 5px;">
			</div>
		</div><!-- End of .actions -->
	<?= Formulario::fin(); ?>
</section><!-- End of #content -->