<div class="grid_4">
	<form method="post" action="#" class="box validate">

		<div class="header">
			<h2>Full Width Grid with Inline Label</h2>
		</div>

		<div class="content">

			<p class="_100 small" style="padding-top: 10px;">
				<label for="f9_ban" class=inline >Bank Account Number:</label>
				<input data-error-type=inline type="text" class=required name=f9_ban id=f9_ban pattern="^\d{1,10}$" />
			</p>

			<p class="_100 small">
				<label for="f9_name" class=inline >Name:</label>
				<input data-error-type=inline type="text" class=required name=f9_name id=f9_name />
			</p>

			<p class="_100 small" style="padding-bottom: 10px;">
				<label for="f9_pin" class=inline >PIN:</label>
				<input data-error-type=inline type="password" class=required name=f9_pin id=f9_pin />
			</p>

		</div><!-- End of .content -->

		<div class="actions">
			<div class="left">
				<input type="reset" value="Cancel" />
			</div>
			<div class="right">
				<input type="submit" value="Send" name=send />
			</div>
		</div><!-- End of .actions -->

	</form><!-- End of .box -->
</div><!-- End of .grid_4 -->