<?php
	$modulo = "Cuentas";
	$seccion = $cuenta ? "Modificar Cuenta" : "Nueva Cuenta";
	$contribuyente = $cuenta ? $cuenta -> contribuyente() : false;
?>

<?= View::partial("base/edicion") ?>
<?= Html::breadcrumbs($controller_name."/".$action_name, $modulo."/".$seccion) ?>

<!-- Here goes the content. -->
<section id="content" class="container_12 clearfix" data-sort=true>
	<?= isset($alerta) ? $alerta : "" ?>
	<h1 class="grid_12"><?= $cuenta ? "Modificar Cuenta" : "Nueva Cuenta" ?></h1>
	<?= Formulario::inicioAjax($cuenta ? $controller_name."/modificar" : $controller_name."/registrar", "contenido", false, "class: grid_12") ?>
	<?php if($cuenta) echo Formulario::oculto("cuenta", $cuenta -> id) ?>
		<fieldset>
			<legend>
				INFORMACIÓN DE LA CUENTA
			</legend>
			<div class="row">
				<p class="_25">
					<label>RFC</label>
					<?= Formulario::rfc("rfc",$cuenta ? $cuenta -> rfc : "","class: required") ?>
				</p>
				<p class="_50">
					<label>Nombre o Razón Social</label>
					<?= Formulario::mayusculas("nombre",$cuenta ? $cuenta -> nombre : "","class: required") ?>
				</p>
				<p class="_25">
					<label>Paquete</label>
					<?php $paquetes = Paquete::reporte("activo = 'SI'"); ?>
					<?= Formulario::selectModelo("paquete",$paquetes,"nombre","id",$cuenta ? $cuenta -> paquete_id  : "","class: search required","data-placeholder: Selecciona Tipo") ?>
				</p>
			</div>
			<div class="row">
				<p class="_25">
					<label>Teléfono de Contacto</label>
					<?= Formulario::numerico("telefono",$cuenta ? $cuenta -> telefono_contacto : "","class: maskPhone required") ?>
				</p>
				<p class="_50">
					<label>Correo Electrónico</label>
					<?= Formulario::texto("correo",$cuenta ? $cuenta -> correo_contacto : "","class: email required") ?>
				</p>
				<p class="_25">
					<label>Contrato</label>
					<?= Formulario::select("tipo_contrato",array("ANUAL" => "ANUAL","SEMESTRAL" => "SEMESTRAL","MENSUAL" => "MENSUAL"),$cuenta ? $cuenta -> tipo_contrato  : "ANUAL","class: search required","data-placeholder: Selecciona Estado") ?>
				</p>
			</div>
		</fieldset>
		<fieldset>
			<legend>
				INFORMACIÓN DEL CONTRIBUYENTE
			</legend>
			<div class="row">
				<p class="_50">
					<label>Calle</label>
					<?= Formulario::mayusculas("calle",$contribuyente ? $contribuyente -> calle : "") ?>
				</p>
				<p class="_25">
					<label>No. Exterior</label>
					<?= Formulario::mayusculas("exterior",$contribuyente ? $contribuyente -> exterior : "") ?>
				</p>
				<p class="_25">
					<label>No. Interior</label>
					<?= Formulario::mayusculas("interior",$contribuyente ? $contribuyente -> interior : "") ?>
				</p>
			</div>
			<div class="row">
				<p class="_50">
					<label>Colonia</label>
					<?= Formulario::mayusculas("colonia",$contribuyente ? $contribuyente -> colonia : "") ?>
				</p>
				<p class="_25">
					<label>Localidad</label>
					<?= Formulario::mayusculas("localidad",$contribuyente ? $contribuyente -> localidad : "") ?>
				</p>
				<p class="_25">
					<label>Código Postal</label>
					<?= Formulario::numerico("cpostal",$contribuyente ? $contribuyente -> cpostal : "","class: digits","minlength: 5", "maxlength: 5") ?>
				</p>
			</div>
			<div class="row">
				<p class="_50">
					<label>Municipio</label>
					<?= Formulario::mayusculas("municipio",$contribuyente ? $contribuyente -> municipio : "") ?>
				</p>
				<p class="_25">
					<label>Estado</label>
					<?= Formulario::selectEstados("estado",$contribuyente ? $contribuyente -> estado  : "","class: search","data-placeholder: Selecciona Estado") ?>
				</p>
				<p class="_25">
					<label>País</label>
					<?= Formulario::select("pais",array("","MÉXICO" => "MÉXICO"),$contribuyente ? $contribuyente -> pais : "","class: search","data-placeholder: Selecciona País") ?>
				</p>
			</div>
		</fieldset>
		<div class="actions">
			<div class="right" style="margin: 5px;">
				<?php if($cuenta){ ?>
					<?= Html::linkAjax("cuentas/resetearPassword/".$cuenta -> id,"Cambiar Contraseña","contenido","class: button red"); ?>
				<?php } ?>
				<?= Formulario::submit($cuenta ? "Modificar" : "Registrar") ?>
			</div>
			<div class="left" style="margin: 5px;">
				<?= Html::linkAjax("cuentas/reporte","Regresar","contenido","class: button red"); ?>
			</div>
		</div><!-- End of .actions -->
	<?= Formulario::fin(); ?>
</section><!-- E
	nd of #content -->