<?php
	$modulo = "Cuentas";
	$seccion = $cuenta ? "Modificar Cuenta" : "Nueva Cuenta";
?>

<?= View::partial("base/edicion") ?>
<?= Html::breadcrumbs($controller_name."/".$action_name, $modulo."/".$seccion) ?>

<!-- Here goes the content. -->
<section id="content" class="container_12 clearfix" data-sort=true>
	<?= isset($alerta) ? $alerta : "" ?>
	<h1 class="grid_12"><?= $cuenta ? "Modificar Cuenta" : "Nueva Cuenta" ?></h1>
	<?= Formulario::inicioAjax($cuenta ? $controller_name."/modificar" : $controller_name."/registrar", "contenido", false, "class: grid_12") ?>
	<?php if($cuenta) echo Formulario::oculto("cuenta", $cuenta -> id) ?>
		<fieldset>
			<legend>
				INFORMACIÓN DE LA CUENTA
			</legend>
			<div class="row">
				<p class="_25">
					<label>RFC</label>
					<?= Formulario::rfc("rfc",$cuenta ? $cuenta -> rfc : "","class: required") ?>
				</p>
				<p class="_50">
					<label>Nombre o Razón Social</label>
					<?= Formulario::mayusculas("nombre",$cuenta ? $cuenta -> nombre : "","class: required") ?>
				</p>
				<p class="_25">
					<label>Activo</label>
					<?= Formulario::select("activo",array("SI" => "SI","NO" => "NO"),$cuenta ? $cuenta -> activo  : "SI","class: search required","data-placeholder: Selecciona Estado") ?>
				</p>
			</div>
			<div class="row">
				<p class="_25">
					<label>Teléfono</label>
					<?= Formulario::numerico("telefono",$cuenta ? $cuenta -> telefono_contacto : "","class: maskPhone") ?>
				</p>
				<p class="_25">
					<label>Celular</label>
					<?= Formulario::numerico("celular",$cuenta ? $cuenta -> celular_contacto : "","class: maskPhone") ?>
				</p>
				<p class="_50">
					<label>Correo Electrónico</label>
					<?= Formulario::texto("correo",$cuenta ? $cuenta -> correo_contacto : "","class: email") ?>
				</p>
			</div>
		</fieldset>
		<div class="actions">
			<div class="right" style="margin: 5px;">
				<?= Formulario::submit($cuenta ? "Modificar" : "Registrar") ?>
			</div>
			<div class="left" style="margin: 5px;">
				<?= Formulario::reset("Cancelar") ?>
			</div>
		</div><!-- End of .actions -->
	<?= Formulario::fin(); ?>
</section><!-- End of #content -->